from jboss/infinispan-server:9.3.0.Final

ADD ./src/main/resources/clustered.xml /opt/jboss/infinispan-server/standalone/configuration/clustered.xml
ADD ./target/analyzers.jar /opt/jboss/infinispan-server/standalone/deployments/analyzers.jar